#############################################################################
# Makefile for building: reminder_calendar
# Generated by qmake (3.1) (Qt 6.11.1)
# Project:  reminder_calendar.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile reminder_calendar.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I. -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I. -I/usr/lib64/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = reminder_calendar1.0.0
DISTDIR = /home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar/.tmp/reminder_calendar1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib64
LIBS          = $(SUBLIBS) /usr/lib64/libQt6Widgets.so /usr/lib64/libQt6Gui.so /usr/lib64/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = JsonFile.cpp \
		main.cpp \
		gui/AddView.cpp \
		gui/CalendarView.cpp \
		gui/EditView.cpp \
		gui/EditWidget.cpp \
		gui/ListView.cpp \
		gui/ListWidget.cpp \
		gui/ReminderView.cpp \
		gui/ReminderWidget.cpp \
		gui/Utilities.cpp \
		gui/ViewManager.cpp \
		model/AbstractReminder.cpp \
		model/Deadline.cpp \
		model/Event.cpp \
		model/Memo.cpp \
		model/ReminderList.cpp moc_AddView.cpp \
		moc_CalendarView.cpp \
		moc_EditView.cpp \
		moc_EditWidget.cpp \
		moc_ListView.cpp \
		moc_ListWidget.cpp \
		moc_ReminderView.cpp \
		moc_ReminderWidget.cpp \
		moc_ViewManager.cpp
OBJECTS       = JsonFile.o \
		main.o \
		AddView.o \
		CalendarView.o \
		EditView.o \
		EditWidget.o \
		ListView.o \
		ListWidget.o \
		ReminderView.o \
		ReminderWidget.o \
		Utilities.o \
		ViewManager.o \
		AbstractReminder.o \
		Deadline.o \
		Event.o \
		Memo.o \
		ReminderList.o \
		moc_AddView.o \
		moc_CalendarView.o \
		moc_EditView.o \
		moc_EditWidget.o \
		moc_ListView.o \
		moc_ListWidget.o \
		moc_ReminderView.o \
		moc_ReminderWidget.o \
		moc_ViewManager.o
DIST          = /usr/lib64/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt6/mkspecs/common/unix.conf \
		/usr/lib64/qt6/mkspecs/common/linux.conf \
		/usr/lib64/qt6/mkspecs/common/sanitize.conf \
		/usr/lib64/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt6/mkspecs/common/g++-base.conf \
		/usr/lib64/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt6/mkspecs/qconfig.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testinternals_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_MimeTreeParserCore.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_MimeTreeParserWidgets.pri \
		/usr/lib64/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt6/mkspecs/features/qt_config.prf \
		/usr/lib64/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt6/mkspecs/features/toolchain.prf \
		/usr/lib64/qt6/mkspecs/features/default_pre.prf \
		/usr/lib64/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt6/mkspecs/features/default_post.prf \
		/usr/lib64/qt6/mkspecs/features/warn_on.prf \
		/usr/lib64/qt6/mkspecs/features/permissions.prf \
		/usr/lib64/qt6/mkspecs/features/qt.prf \
		/usr/lib64/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib64/qt6/mkspecs/features/resources.prf \
		/usr/lib64/qt6/mkspecs/features/moc.prf \
		/usr/lib64/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt6/mkspecs/features/uic.prf \
		/usr/lib64/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt6/mkspecs/features/file_copies.prf \
		/usr/lib64/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt6/mkspecs/features/exceptions.prf \
		/usr/lib64/qt6/mkspecs/features/yacc.prf \
		/usr/lib64/qt6/mkspecs/features/lex.prf \
		reminder_calendar.pro JsonFile.h \
		gui/AddView.h \
		gui/CalendarView.h \
		gui/EditView.h \
		gui/EditWidget.h \
		gui/ListView.h \
		gui/ListWidget.h \
		gui/ReminderView.h \
		gui/ReminderWidget.h \
		gui/Utilities.h \
		gui/ViewManager.h \
		model/AbstractReminder.h \
		model/ConstReminderVisitor.h \
		model/Deadline.h \
		model/Event.h \
		model/Memo.h \
		model/ReminderList.h \
		model/ReminderVisitor.h JsonFile.cpp \
		main.cpp \
		gui/AddView.cpp \
		gui/CalendarView.cpp \
		gui/EditView.cpp \
		gui/EditWidget.cpp \
		gui/ListView.cpp \
		gui/ListWidget.cpp \
		gui/ReminderView.cpp \
		gui/ReminderWidget.cpp \
		gui/Utilities.cpp \
		gui/ViewManager.cpp \
		model/AbstractReminder.cpp \
		model/Deadline.cpp \
		model/Event.cpp \
		model/Memo.cpp \
		model/ReminderList.cpp
QMAKE_TARGET  = reminder_calendar
DESTDIR       = 
TARGET        = reminder_calendar


first: all
####### Build rules

reminder_calendar:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: reminder_calendar.pro /usr/lib64/qt6/mkspecs/linux-g++/qmake.conf /usr/lib64/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt6/mkspecs/common/unix.conf \
		/usr/lib64/qt6/mkspecs/common/linux.conf \
		/usr/lib64/qt6/mkspecs/common/sanitize.conf \
		/usr/lib64/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt6/mkspecs/common/g++-base.conf \
		/usr/lib64/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt6/mkspecs/qconfig.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testinternals_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_MimeTreeParserCore.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_MimeTreeParserWidgets.pri \
		/usr/lib64/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt6/mkspecs/features/qt_config.prf \
		/usr/lib64/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt6/mkspecs/features/toolchain.prf \
		/usr/lib64/qt6/mkspecs/features/default_pre.prf \
		/usr/lib64/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt6/mkspecs/features/default_post.prf \
		/usr/lib64/qt6/mkspecs/features/warn_on.prf \
		/usr/lib64/qt6/mkspecs/features/permissions.prf \
		/usr/lib64/qt6/mkspecs/features/qt.prf \
		/usr/lib64/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib64/qt6/mkspecs/features/resources.prf \
		/usr/lib64/qt6/mkspecs/features/moc.prf \
		/usr/lib64/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt6/mkspecs/features/uic.prf \
		/usr/lib64/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt6/mkspecs/features/file_copies.prf \
		/usr/lib64/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt6/mkspecs/features/exceptions.prf \
		/usr/lib64/qt6/mkspecs/features/yacc.prf \
		/usr/lib64/qt6/mkspecs/features/lex.prf \
		reminder_calendar.pro \
		/usr/lib64/libQt6Widgets.prl \
		/usr/lib64/libQt6Gui.prl \
		/usr/lib64/libQt6Core.prl
	$(QMAKE) -o Makefile reminder_calendar.pro
/usr/lib64/qt6/mkspecs/features/spec_pre.prf:
/usr/lib64/qt6/mkspecs/common/unix.conf:
/usr/lib64/qt6/mkspecs/common/linux.conf:
/usr/lib64/qt6/mkspecs/common/sanitize.conf:
/usr/lib64/qt6/mkspecs/common/gcc-base.conf:
/usr/lib64/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt6/mkspecs/common/g++-base.conf:
/usr/lib64/qt6/mkspecs/common/g++-unix.conf:
/usr/lib64/qt6/mkspecs/qconfig.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_testinternals_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_MimeTreeParserCore.pri:
/usr/lib64/qt6/mkspecs/modules/qt_MimeTreeParserWidgets.pri:
/usr/lib64/qt6/mkspecs/features/qt_functions.prf:
/usr/lib64/qt6/mkspecs/features/qt_config.prf:
/usr/lib64/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib64/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt6/mkspecs/features/toolchain.prf:
/usr/lib64/qt6/mkspecs/features/default_pre.prf:
/usr/lib64/qt6/mkspecs/features/resolve_config.prf:
/usr/lib64/qt6/mkspecs/features/default_post.prf:
/usr/lib64/qt6/mkspecs/features/warn_on.prf:
/usr/lib64/qt6/mkspecs/features/permissions.prf:
/usr/lib64/qt6/mkspecs/features/qt.prf:
/usr/lib64/qt6/mkspecs/features/resources_functions.prf:
/usr/lib64/qt6/mkspecs/features/resources.prf:
/usr/lib64/qt6/mkspecs/features/moc.prf:
/usr/lib64/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt6/mkspecs/features/uic.prf:
/usr/lib64/qt6/mkspecs/features/unix/thread.prf:
/usr/lib64/qt6/mkspecs/features/qmake_use.prf:
/usr/lib64/qt6/mkspecs/features/file_copies.prf:
/usr/lib64/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt6/mkspecs/features/exceptions.prf:
/usr/lib64/qt6/mkspecs/features/yacc.prf:
/usr/lib64/qt6/mkspecs/features/lex.prf:
reminder_calendar.pro:
/usr/lib64/libQt6Widgets.prl:
/usr/lib64/libQt6Gui.prl:
/usr/lib64/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile reminder_calendar.pro

qmake_all: FORCE


all: Makefile reminder_calendar

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib64/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents JsonFile.h gui/AddView.h gui/CalendarView.h gui/EditView.h gui/EditWidget.h gui/ListView.h gui/ListWidget.h gui/ReminderView.h gui/ReminderWidget.h gui/Utilities.h gui/ViewManager.h model/AbstractReminder.h model/ConstReminderVisitor.h model/Deadline.h model/Event.h model/Memo.h model/ReminderList.h model/ReminderVisitor.h $(DISTDIR)/
	$(COPY_FILE) --parents JsonFile.cpp main.cpp gui/AddView.cpp gui/CalendarView.cpp gui/EditView.cpp gui/EditWidget.cpp gui/ListView.cpp gui/ListWidget.cpp gui/ReminderView.cpp gui/ReminderWidget.cpp gui/Utilities.cpp gui/ViewManager.cpp model/AbstractReminder.cpp model/Deadline.cpp model/Event.cpp model/Memo.cpp model/ReminderList.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib64/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib64/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_AddView.cpp moc_CalendarView.cpp moc_EditView.cpp moc_EditWidget.cpp moc_ListView.cpp moc_ListWidget.cpp moc_ReminderView.cpp moc_ReminderWidget.cpp moc_ViewManager.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_AddView.cpp moc_CalendarView.cpp moc_EditView.cpp moc_EditWidget.cpp moc_ListView.cpp moc_ListWidget.cpp moc_ReminderView.cpp moc_ReminderWidget.cpp moc_ViewManager.cpp
moc_AddView.cpp: gui/AddView.h \
		model/AbstractReminder.h \
		model/ReminderVisitor.h \
		model/ConstReminderVisitor.h \
		gui/ReminderWidget.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar -I/home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-redhat-linux -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-redhat-linux/16/include -I/usr/local/include -I/usr/include gui/AddView.h -o moc_AddView.cpp

moc_CalendarView.cpp: gui/CalendarView.h \
		model/ReminderList.h \
		model/AbstractReminder.h \
		model/ReminderVisitor.h \
		model/ConstReminderVisitor.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar -I/home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-redhat-linux -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-redhat-linux/16/include -I/usr/local/include -I/usr/include gui/CalendarView.h -o moc_CalendarView.cpp

moc_EditView.cpp: gui/EditView.h \
		gui/EditWidget.h \
		model/ConstReminderVisitor.h \
		model/AbstractReminder.h \
		model/ReminderVisitor.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar -I/home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-redhat-linux -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-redhat-linux/16/include -I/usr/local/include -I/usr/include gui/EditView.h -o moc_EditView.cpp

moc_EditWidget.cpp: gui/EditWidget.h \
		model/ConstReminderVisitor.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar -I/home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-redhat-linux -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-redhat-linux/16/include -I/usr/local/include -I/usr/include gui/EditWidget.h -o moc_EditWidget.cpp

moc_ListView.cpp: gui/ListView.h \
		model/ReminderList.h \
		model/AbstractReminder.h \
		model/ReminderVisitor.h \
		model/ConstReminderVisitor.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar -I/home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-redhat-linux -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-redhat-linux/16/include -I/usr/local/include -I/usr/include gui/ListView.h -o moc_ListView.cpp

moc_ListWidget.cpp: gui/ListWidget.h \
		model/ConstReminderVisitor.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar -I/home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-redhat-linux -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-redhat-linux/16/include -I/usr/local/include -I/usr/include gui/ListWidget.h -o moc_ListWidget.cpp

moc_ReminderView.cpp: gui/ReminderView.h \
		model/AbstractReminder.h \
		model/ReminderVisitor.h \
		model/ConstReminderVisitor.h \
		gui/ReminderWidget.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar -I/home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-redhat-linux -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-redhat-linux/16/include -I/usr/local/include -I/usr/include gui/ReminderView.h -o moc_ReminderView.cpp

moc_ReminderWidget.cpp: gui/ReminderWidget.h \
		model/ConstReminderVisitor.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar -I/home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-redhat-linux -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-redhat-linux/16/include -I/usr/local/include -I/usr/include gui/ReminderWidget.h -o moc_ReminderWidget.cpp

moc_ViewManager.cpp: gui/ViewManager.h \
		gui/ListView.h \
		model/ReminderList.h \
		model/AbstractReminder.h \
		model/ReminderVisitor.h \
		model/ConstReminderVisitor.h \
		gui/ReminderView.h \
		gui/ReminderWidget.h \
		gui/EditView.h \
		gui/EditWidget.h \
		gui/AddView.h \
		JsonFile.h \
		gui/CalendarView.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar -I/home/jen1315/Documenti/unipd/prog_ogg/progetto2/reminder_calendar -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-redhat-linux -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-redhat-linux/16/include -I/usr/local/include -I/usr/include gui/ViewManager.h -o moc_ViewManager.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

JsonFile.o: JsonFile.cpp JsonFile.h \
		model/ReminderList.h \
		model/AbstractReminder.h \
		model/ReminderVisitor.h \
		model/ConstReminderVisitor.h \
		model/Event.h \
		model/Deadline.h \
		model/Memo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JsonFile.o JsonFile.cpp

main.o: main.cpp JsonFile.h \
		model/ReminderList.h \
		model/AbstractReminder.h \
		model/ReminderVisitor.h \
		model/ConstReminderVisitor.h \
		gui/ViewManager.h \
		gui/ListView.h \
		gui/ReminderView.h \
		gui/ReminderWidget.h \
		gui/EditView.h \
		gui/EditWidget.h \
		gui/AddView.h \
		gui/CalendarView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

AddView.o: gui/AddView.cpp gui/AddView.h \
		model/AbstractReminder.h \
		model/ReminderVisitor.h \
		model/ConstReminderVisitor.h \
		gui/ReminderWidget.h \
		model/Event.h \
		model/Deadline.h \
		model/Memo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AddView.o gui/AddView.cpp

CalendarView.o: gui/CalendarView.cpp gui/CalendarView.h \
		model/ReminderList.h \
		model/AbstractReminder.h \
		model/ReminderVisitor.h \
		model/ConstReminderVisitor.h \
		model/Event.h \
		model/Deadline.h \
		model/Memo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CalendarView.o gui/CalendarView.cpp

EditView.o: gui/EditView.cpp gui/EditView.h \
		gui/EditWidget.h \
		model/ConstReminderVisitor.h \
		model/AbstractReminder.h \
		model/ReminderVisitor.h \
		gui/Utilities.h \
		model/Event.h \
		model/Deadline.h \
		model/Memo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EditView.o gui/EditView.cpp

EditWidget.o: gui/EditWidget.cpp gui/EditWidget.h \
		model/ConstReminderVisitor.h \
		model/Event.h \
		model/AbstractReminder.h \
		model/ReminderVisitor.h \
		model/Deadline.h \
		model/Memo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EditWidget.o gui/EditWidget.cpp

ListView.o: gui/ListView.cpp gui/ListView.h \
		model/ReminderList.h \
		model/AbstractReminder.h \
		model/ReminderVisitor.h \
		model/ConstReminderVisitor.h \
		gui/ListWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ListView.o gui/ListView.cpp

ListWidget.o: gui/ListWidget.cpp gui/ListWidget.h \
		model/ConstReminderVisitor.h \
		model/Event.h \
		model/AbstractReminder.h \
		model/ReminderVisitor.h \
		model/Deadline.h \
		model/Memo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ListWidget.o gui/ListWidget.cpp

ReminderView.o: gui/ReminderView.cpp gui/ReminderView.h \
		model/AbstractReminder.h \
		model/ReminderVisitor.h \
		model/ConstReminderVisitor.h \
		gui/ReminderWidget.h \
		gui/Utilities.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ReminderView.o gui/ReminderView.cpp

ReminderWidget.o: gui/ReminderWidget.cpp gui/ReminderWidget.h \
		model/ConstReminderVisitor.h \
		model/Event.h \
		model/AbstractReminder.h \
		model/ReminderVisitor.h \
		model/Deadline.h \
		model/Memo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ReminderWidget.o gui/ReminderWidget.cpp

Utilities.o: gui/Utilities.cpp gui/Utilities.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Utilities.o gui/Utilities.cpp

ViewManager.o: gui/ViewManager.cpp gui/ViewManager.h \
		gui/ListView.h \
		model/ReminderList.h \
		model/AbstractReminder.h \
		model/ReminderVisitor.h \
		model/ConstReminderVisitor.h \
		gui/ReminderView.h \
		gui/ReminderWidget.h \
		gui/EditView.h \
		gui/EditWidget.h \
		gui/AddView.h \
		JsonFile.h \
		gui/CalendarView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ViewManager.o gui/ViewManager.cpp

AbstractReminder.o: model/AbstractReminder.cpp model/AbstractReminder.h \
		model/ReminderVisitor.h \
		model/ConstReminderVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AbstractReminder.o model/AbstractReminder.cpp

Deadline.o: model/Deadline.cpp model/Deadline.h \
		model/Memo.h \
		model/AbstractReminder.h \
		model/ReminderVisitor.h \
		model/ConstReminderVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Deadline.o model/Deadline.cpp

Event.o: model/Event.cpp model/Event.h \
		model/AbstractReminder.h \
		model/ReminderVisitor.h \
		model/ConstReminderVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Event.o model/Event.cpp

Memo.o: model/Memo.cpp model/Memo.h \
		model/AbstractReminder.h \
		model/ReminderVisitor.h \
		model/ConstReminderVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Memo.o model/Memo.cpp

ReminderList.o: model/ReminderList.cpp model/ReminderList.h \
		model/AbstractReminder.h \
		model/ReminderVisitor.h \
		model/ConstReminderVisitor.h \
		model/Event.h \
		model/Deadline.h \
		model/Memo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ReminderList.o model/ReminderList.cpp

moc_AddView.o: moc_AddView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AddView.o moc_AddView.cpp

moc_CalendarView.o: moc_CalendarView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CalendarView.o moc_CalendarView.cpp

moc_EditView.o: moc_EditView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_EditView.o moc_EditView.cpp

moc_EditWidget.o: moc_EditWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_EditWidget.o moc_EditWidget.cpp

moc_ListView.o: moc_ListView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ListView.o moc_ListView.cpp

moc_ListWidget.o: moc_ListWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ListWidget.o moc_ListWidget.cpp

moc_ReminderView.o: moc_ReminderView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ReminderView.o moc_ReminderView.cpp

moc_ReminderWidget.o: moc_ReminderWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ReminderWidget.o moc_ReminderWidget.cpp

moc_ViewManager.o: moc_ViewManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ViewManager.o moc_ViewManager.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

