######################################################################
# Automatically generated by qmake (3.1) Sat Dec 27 11:45:26 2025
######################################################################

TEMPLATE = app
TARGET = reminder_calendar
INCLUDEPATH += .
QT += widgets

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += JsonFile.h \
           gui/AddView.h \
           gui/ReminderListView.h \
           gui/ReminderView.h \
           gui/ReminderWidget.h \
           gui/ViewManager.h \
           model/AbstractReminder.h \
           model/Deadline.h \
           model/Event.h \
           model/Memo.h \
           model/ReminderList.h \
           model/ReminderVisitor.h
SOURCES += JsonFile.cpp \
           gui/AddView.cpp \
           gui/ReminderListView.cpp \
           gui/ReminderView.cpp \
           gui/ReminderWidget.cpp \
           gui/ViewManager.cpp \
           model/AbstractReminder.cpp \
           model/Deadline.cpp \
           model/Event.cpp \
           model/Memo.cpp \
           model/ReminderList.cpp
